[package]
name = "bok"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
hex = "0.4.3"
sha2 = "0.10.9"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.1.0"
